In [1]:
import pandas as pd

raw_df = pd.read_csv("dataSets/data.csv", index_col = 0)
df = raw_df.set_index("ID").drop(columns=["Photo", "Flag", "Club Logo"])

In [2]:
df.head()

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
ID,,,,,,,,,,,,,,,,,,,,,
158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,2202,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,2228,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,2143,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,1471,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,2281,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [3]:
labels = df.columns.to_list()

In [4]:
labels

['Name',
 'Age',
 'Nationality',
 'Overall',
 'Potential',
 'Club',
 'Value',
 'Wage',
 'Special',
 'Preferred Foot',
 'International Reputation',
 'Weak Foot',
 'Skill Moves',
 'Work Rate',
 'Body Type',
 'Real Face',
 'Position',
 'Jersey Number',
 'Joined',
 'Loaned From',
 'Contract Valid Until',
 'Height',
 'Weight',
 'LS',
 'ST',
 'RS',
 'LW',
 'LF',
 'CF',
 'RF',
 'RW',
 'LAM',
 'CAM',
 'RAM',
 'LM',
 'LCM',
 'CM',
 'RCM',
 'RM',
 'LWB',
 'LDM',
 'CDM',
 'RDM',
 'RWB',
 'LB',
 'LCB',
 'CB',
 'RCB',
 'RB',
 'Crossing',
 'Finishing',
 'HeadingAccuracy',
 'ShortPassing',
 'Volleys',
 'Dribbling',
 'Curve',
 'FKAccuracy',
 'LongPassing',
 'BallControl',
 'Acceleration',
 'SprintSpeed',
 'Agility',
 'Reactions',
 'Balance',
 'ShotPower',
 'Jumping',
 'Stamina',
 'Strength',
 'LongShots',
 'Aggression',
 'Interceptions',
 'Positioning',
 'Vision',
 'Penalties',
 'Composure',
 'Marking',
 'StandingTackle',
 'SlidingTackle',
 'GKDiving',
 'GKHandling',
 'GKKicking',
 'GKPositioning',
 'GKReflexes',
 'Release Clause']

In [5]:
labels[16]

'Position'

In [6]:
position_labels = labels[23:49]

In [7]:
position_labels.append(labels[16])
position_labels.append("Name")

In [8]:
position_labels

['LS',
 'ST',
 'RS',
 'LW',
 'LF',
 'CF',
 'RF',
 'RW',
 'LAM',
 'CAM',
 'RAM',
 'LM',
 'LCM',
 'CM',
 'RCM',
 'RM',
 'LWB',
 'LDM',
 'CDM',
 'RDM',
 'RWB',
 'LB',
 'LCB',
 'CB',
 'RCB',
 'RB',
 'Position',
 'Name']

In [9]:
df_position = df[position_labels]

In [10]:
df_position.head()
df_position.set_index("Name")
df_position.dropna(inplace=True)

c:\users\morpheus\desktop\datascience\datascience\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [11]:
df_position.set_index("Name", inplace=True)
df_position.head()

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Position
Name,,,,,,,,,,,,,,,,,,,,,
L. Messi,88+2,88+2,88+2,92+2,93+2,93+2,93+2,92+2,93+2,93+2,...,61+2,61+2,61+2,64+2,59+2,47+2,47+2,47+2,59+2,RF
Cristiano Ronaldo,91+3,91+3,91+3,89+3,90+3,90+3,90+3,89+3,88+3,88+3,...,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3,ST
Neymar Jr,84+3,84+3,84+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,...,60+3,60+3,60+3,65+3,60+3,47+3,47+3,47+3,60+3,LW
K. De Bruyne,82+3,82+3,82+3,87+3,87+3,87+3,87+3,87+3,88+3,88+3,...,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3,RCM
E. Hazard,83+3,83+3,83+3,89+3,88+3,88+3,88+3,89+3,89+3,89+3,...,63+3,63+3,63+3,66+3,60+3,49+3,49+3,49+3,60+3,LF

In [12]:
df_position.describe()

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Position
count,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,...,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122
unique,93,93,93,105,102,102,102,105,101,101,...,99,99,99,95,98,108,108,108,98,26
top,61+2,61+2,61+2,63+2,61+2,61+2,61+2,63+2,61+2,61+2,...,62+2,62+2,62+2,61+2,61+2,63+2,63+2,63+2,61+2,ST
freq,705,705,705,745,713,713,713,745,744,744,...,660,660,660,713,669,634,634,634,669,2152

In [13]:
df_position[position_labels[:-2]].head()

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
Name,,,,,,,,,,,,,,,,,,,,,
L. Messi,88+2,88+2,88+2,92+2,93+2,93+2,93+2,92+2,93+2,93+2,...,64+2,61+2,61+2,61+2,64+2,59+2,47+2,47+2,47+2,59+2
Cristiano Ronaldo,91+3,91+3,91+3,89+3,90+3,90+3,90+3,89+3,88+3,88+3,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,84+3,84+3,84+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,...,65+3,60+3,60+3,60+3,65+3,60+3,47+3,47+3,47+3,60+3
K. De Bruyne,82+3,82+3,82+3,87+3,87+3,87+3,87+3,87+3,88+3,88+3,...,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3
E. Hazard,83+3,83+3,83+3,89+3,88+3,88+3,88+3,89+3,89+3,89+3,...,66+3,63+3,63+3,63+3,66+3,60+3,49+3,49+3,49+3,60+3

In [14]:
# for label in position_labels[:-2]:
#     df_position.eval(f'{label}_num = {label}', inplace=True)
# df_position.head()
# df_position['LS'] = df_position['LS'].str.split(pat='+', expand=True)[0]
# split_str = df_position['ST'].str.split(pat='+', expand=True)
# split_str[0] = pd.to_numeric(split_str[0])
# split_str[1] = pd.to_numeric(split_str[1])
# split_str['sum'] = split_str.sum(axis=1)
# split_str.head()

for label in position_labels[:-2]:
    split_str = df_position[label].str.split(pat='+', expand=True)
    split_str[0] = pd.to_numeric(split_str[0])
    split_str[1] = pd.to_numeric(split_str[1])
    df_position[label] = split_str.sum(axis=1)
df_position.head()

c:\users\morpheus\desktop\datascience\datascience\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Position
Name,,,,,,,,,,,,,,,,,,,,,
L. Messi,90,90,90,94,95,95,95,94,95,95,...,63,63,63,66,61,49,49,49,61,RF
Cristiano Ronaldo,94,94,94,92,93,93,93,92,91,91,...,64,64,64,68,64,56,56,56,64,ST
Neymar Jr,87,87,87,92,92,92,92,92,92,92,...,63,63,63,68,63,50,50,50,63,LW
K. De Bruyne,85,85,85,90,90,90,90,90,91,91,...,80,80,80,80,76,69,69,69,76,RCM
E. Hazard,86,86,86,92,91,91,91,92,92,92,...,66,66,66,69,63,52,52,52,63,LF

In [15]:
df_pos_lw = df_position[df_position['Position'] == 'LW']
df_pos_lw['max'] = df_pos_lw.max(axis=1)
df_pos_lw.head()

c:\users\morpheus\desktop\datascience\datascience\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Position,max
Name,,,,,,,,,,,,,,,,,,,,,
Neymar Jr,87,87,87,92,92,92,92,92,92,92,...,63,63,68,63,50,50,50,63,LW,92
L. Insigne,81,81,81,89,88,88,88,89,89,89,...,61,61,66,61,47,47,47,61,LW,89
Isco,79,79,79,87,86,86,86,87,89,89,...,76,76,75,71,66,66,66,71,LW,89
Coutinho,82,82,82,89,88,88,88,89,90,90,...,73,73,74,70,61,61,61,70,LW,90
L. Sané,84,84,84,86,86,86,86,86,84,84,...,61,61,67,63,54,54,54,63,LW,86

In [16]:
position_labels = position_labels[:-2]

In [17]:
for label in position_labels:
    df_pos_lw[label] = df_pos_lw['max'] - df_pos_lw[label]
df_pos_lw.head()

c:\users\morpheus\desktop\datascience\datascience\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Position,max
Name,,,,,,,,,,,,,,,,,,,,,
Neymar Jr,5,5,5,0,0,0,0,0,0,0,...,29,29,24,29,42,42,42,29,LW,92
L. Insigne,8,8,8,0,1,1,1,0,0,0,...,28,28,23,28,42,42,42,28,LW,89
Isco,10,10,10,2,3,3,3,2,0,0,...,13,13,14,18,23,23,23,18,LW,89
Coutinho,8,8,8,1,2,2,2,1,0,0,...,17,17,16,20,29,29,29,20,LW,90
L. Sané,2,2,2,0,0,0,0,0,2,2,...,25,25,19,23,32,32,32,23,LW,86

In [18]:
se_lw_diff = dict()
for label in position_labels:
    se_lw_diff[label] = df_pos_lw[[label]].mean(axis=0, numeric_only=True)[0]
se_lw_diff['Pos'] = 'LW'
se_lw_diff

{'LS': 3.493438320209974,
 'ST': 3.493438320209974,
 'RS': 3.493438320209974,
 'LW': 0.2887139107611549,
 'LF': 1.272965879265092,
 'CF': 1.272965879265092,
 'RF': 1.272965879265092,
 'RW': 0.2887139107611549,
 'LAM': 1.6062992125984252,
 'CAM': 1.6062992125984252,
 'RAM': 1.6062992125984252,
 'LM': 0.9658792650918635,
 'LCM': 7.062992125984252,
 'CM': 7.062992125984252,
 'RCM': 7.062992125984252,
 'RM': 0.9658792650918635,
 'LWB': 13.149606299212598,
 'LDM': 16.8503937007874,
 'CDM': 16.8503937007874,
 'RDM': 16.8503937007874,
 'RWB': 13.149606299212598,
 'LB': 15.766404199475065,
 'LCB': 22.212598425196852,
 'CB': 22.212598425196852,
 'RCB': 22.212598425196852,
 'RB': 15.766404199475065,
 'Pos': 'LW'}

In [19]:
ext_position_labels = position_labels.copy()
ext_position_labels.append('Pos')

In [20]:
df_pos_diff = pd.DataFrame([se_lw_diff])
df_pos_diff.set_index('Pos')

,CAM,CB,CDM,CF,CM,LAM,LB,LCB,LCM,LDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
Pos,,,,,,,,,,,,,,,,,,,,,
LW,1.606299,22.212598,16.850394,1.272966,7.062992,1.606299,15.766404,22.212598,7.062992,16.850394,...,15.766404,22.212598,7.062992,16.850394,1.272966,0.965879,3.493438,0.288714,13.149606,3.493438

In [40]:
df_pos_diff_final = pd.DataFrame()
dict_pos_diff = dict()
for position in position_labels:
    df_pos = df_position[df_position['Position'] == position]
    df_pos['max'] = df_pos.max(axis=1)
    for label in position_labels:
        df_pos[label] = df_pos['max'] - df_pos[label]
    arr_pos_diff = []
    for label2 in position_labels:
        arr_pos_diff.append(df_pos[[label2]].mean(axis=0, numeric_only=True)[0])
    dict_pos_diff[position] = arr_pos_diff
#         dict_pos_diff['Pos'] = position
#         if df_pos_diff_final.empty:
#             df_pos_diff_final = pd.DataFrame([dict_pos_diff])
#             df_pos_diff_final.set_index('Pos')
#         else:
#             df_pos_diff_final.append([dict_pos_diff])

c:\users\morpheus\desktop\datascience\datascience\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
c:\users\morpheus\desktop\datascience\datascience\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [41]:
dict_pos_diff['LW']

[3.493438320209974,
 3.493438320209974,
 3.493438320209974,
 0.2887139107611549,
 1.272965879265092,
 1.272965879265092,
 1.272965879265092,
 0.2887139107611549,
 1.6062992125984252,
 1.6062992125984252,
 1.6062992125984252,
 0.9658792650918635,
 7.062992125984252,
 7.062992125984252,
 7.062992125984252,
 0.9658792650918635,
 13.149606299212598,
 16.8503937007874,
 16.8503937007874,
 16.8503937007874,
 13.149606299212598,
 15.766404199475065,
 22.212598425196852,
 22.212598425196852,
 22.212598425196852,
 15.766404199475065]

In [43]:
df_pos_diff_final = pd.DataFrame.from_dict(dict_pos_diff, orient='index', columns=position_labels)
df_pos_diff_final

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
LS,0.710145,0.710145,0.710145,2.787440,1.657005,1.657005,1.657005,2.787440,3.516908,3.516908,...,17.913043,19.661836,19.661836,19.661836,17.913043,20.198068,22.850242,22.850242,22.850242,20.198068
ST,0.291357,0.291357,0.291357,3.092937,1.749071,1.749071,1.749071,3.092937,3.836431,3.836431,...,18.044145,19.836896,19.836896,19.836896,18.044145,19.933086,22.031599,22.031599,22.031599,19.933086
RS,0.679803,0.679803,0.679803,2.950739,1.788177,1.788177,1.788177,2.950739,3.748768,3.748768,...,17.738916,19.551724,19.551724,19.551724,17.738916,19.886700,22.428571,22.428571,22.428571,19.886700
LW,3.493438,3.493438,3.493438,0.288714,1.272966,1.272966,1.272966,0.288714,1.606299,1.606299,...,13.149606,16.850394,16.850394,16.850394,13.149606,15.766404,22.212598,22.212598,22.212598,15.766404
LF,3.866667,3.866667,3.866667,0.600000,1.133333,1.133333,1.133333,0.600000,0.666667,0.666667,...,14.666667,16.866667,16.866667,16.866667,14.666667,18.000000,24.400000,24.400000,24.400000,18.000000
CF,2.500000,2.500000,2.500000,0.729730,0.878378,0.878378,0.878378,0.729730,1.189189,1.189189,...,15.743243,18.216216,18.216216,18.216216,15.743243,18.432432,23.635135,23.635135,23.635135,18.432432
RF,3.187500,3.187500,3.187500,0.750000,1.125000,1.125000,1.125000,0.750000,1.000000,1.000000,...,14.375000,16.750000,16.750000,16.750000,14.375000,17.375000,23.750000,23.750000,23.750000,17.375000
RW,3.629730,3.629730,3.629730,0.308108,1.324324,1.324324,1.324324,0.308108,1.651351,1.651351,...,13.397297,17.248649,17.248649,17.248649,13.397297,16.159459,22.970270,22.970270,22.970270,16.159459
LAM,4.523810,4.523810,4.523810,0.809524,1.619048,1.619048,1.619048,0.809524,0.857143,0.857143,...,15.047619,17.142857,17.142857,17.142857,15.047619,18.047619,24.809524,24.809524,24.809524,18.047619
CAM,4.377871,4.377871,4.377871,0.963466,1.494781,1.494781,1.494781,0.963466,0.552192,0.552192,...,10.822547,12.111691,12.111691,12.111691,10.822547,13.145094,18.080376,18.080376,18.080376,13.145094
RAM,5.666667,5.666667,5.666667,0.619048,1.619048,1.619048,1.619048,0.619048,0.619048,0.619048,...,12.142857,14.857143,14.857143,14.857143,12.142857,14.952381,22.238095,22.238095,22.238095,14.952381
LM,4.130594,4.130594,4.130594,0.595434,1.778995,1.778995,1.778995,0.595434,1.705936,1.705936,...,10.541553,13.779909,13.779909,13.779909,10.541553,12.930594,18.773516,18.773516,18.773516,12.930594
LCM,6.111392,6.111392,6.111392,3.701266,3.764557,3.764557,3.764557,3.701266,2.443038,2.443038,...,4.549367,3.686076,3.686076,3.686076,4.549367,5.701266,7.205063,7.205063,7.205063,5.701266
CM,5.356528,5.356528,5.356528,2.784075,2.940459,2.940459,2.940459,2.784075,1.515065,1.515065,...,3.570301,2.817791,2.817791,2.817791,3.570301,4.458393,5.939742,5.939742,5.939742,4.458393
RCM,6.099744,6.099744,6.099744,3.902813,3.933504,3.933504,3.933504,3.902813,2.649616,2.649616,...,3.751918,2.879795,2.879795,2.879795,3.751918,4.785166,6.012788,6.012788,6.012788,4.785166
RM,4.126335,4.126335,4.126335,0.639680,1.871886,1.871886,1.871886,0.639680,1.823843,1.823843,...,10.332740,13.645018,13.645018,13.645018,10.332740,12.653025,18.467082,18.467082,18.467082,12.653025
LWB,9.025641,9.025641,9.025641,5.141026,6.923077,6.923077,6.923077,5.141026,6.397436,6.397436,...,0.897436,3.384615,3.384615,3.384615,0.897436,1.230769,3.500000,3.500000,3.500000,1.230769
LDM,7.835391,7.835391,7.835391,6.119342,5.934156,5.934156,5.934156,6.119342,4.514403,4.514403,...,3.353909,1.650206,1.650206,1.650206,3.353909,3.872428,3.740741,3.740741,3.740741,3.872428
CDM,9.095992,9.095992,9.095992,7.610759,7.497890,7.497890,7.497890,7.610759,5.893460,5.893460,...,2.843882,0.681435,0.681435,0.681435,2.843882,2.849156,1.580169,1.580169,1.580169,2.849156
RDM,8.161290,8.161290,8.161290,6.891129,6.560484,6.560484,6.560484,6.891129,5.165323,5.165323,...,3.483871,1.455645,1.455645,1.455645,3.483871,3.883065,3.165323,3.165323,3.165323,3.883065
RWB,8.747126,8.747126,8.747126,4.873563,6.689655,6.689655,6.689655,4.873563,6.183908,6.183908,...,0.770115,3.321839,3.321839,3.321839,0.770115,1.126437,3.264368,3.264368,3.264368,1.126437
LB,9.878215,9.878215,9.878215,6.132375,8.032526,8.032526,8.032526,6.132375,7.528744,7.528744,...,0.651286,3.139939,3.139939,3.139939,0.651286,0.695159,2.340393,2.340393,2.340393,0.695159
LCB,17.597222,17.597222,17.597222,19.030864,18.827160,18.827160,18.827160,19.030864,18.010802,18.010802,...,7.041667,4.520062,4.520062,4.520062,7.041667,5.276235,0.094136,0.094136,0.094136,5.276235
CB,17.069179,17.069179,17.069179,18.782902,18.574241,18.574241,18.574241,18.782902,18.017435,18.017435,...,7.092801,4.987627,4.987627,4.987627,7.092801,5.119235,0.046682,0.046682,0.046682,5.119235
RCB,17.941088,17.941088,17.941088,19.793051,19.376133,19.376133,19.376133,19.793051,18.601208,18.601208,...,7.539275,4.672205,4.672205,4.672205,7.539275,5.631420,0.081571,0.081571,0.081571,5.631420
RB,10.217661,10.217661,10.217661,6.512781,8.401239,8.401239,8.401239,6.512781,7.852053,7.852053,...,0.685515,3.070488,3.070488,3.070488,0.685515,0.687839,2.168087,2.168087,2.168087,0.687839

In [45]:
df_pos_diff_final.to_csv("dataSets/meanPositionDifference.csv")